name: buku_siap_pinjam
description: "Aplikasi baca buku digital dengan GetX"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management & Navigation
  get: ^4.6.6

  # Storage
  shared_preferences: ^2.2.2

  # HTTP & API
  http: ^1.2.0

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Icons
  iconsax: ^0.0.8

  # Reading
  flutter_html: ^3.0.0-beta.2

  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets - Uncomment jika Anda sudah punya file assets
  # assets:
  #   - assets/images/
  #   - assets/icons/
